version: 2.0

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/slack
  slack: circleci/slack@3.4.1

parameters:
  build_amazon:
    type: boolean
    default: false

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - checkout
      - precondition_check:
          requires:
            - checkout
      - download_dependencies:
          requires:
            - checkout
      - build:
          requires:
            - precondition_check
            - download_dependencies
      - sonar_qube:
          requires:
            - precondition_check
      - lint:
          requires:
            - precondition_check
      - unit_test:
          requires:
            - build
            - lint
            - sonar_qube
      - instrumentation_test:
          requires:
            - build
            - lint
            - sonar_qube
      - integration_test:
          requires:
            - build
            - lint
            - sonar_qube
      - automatic_test:
          requires:
            - build
            - lint
            - sonar_qube
      - espresso_test:
          requires:
            - build
            - lint
            - sonar_qube
          filters:
            branches:
              only:
                - master
                - develop
      - deploy_internal:
          requires:
            - unit_test
            - instrumentation_test
            - integration_test
            - automatic_test
            - espresso_test
      - manual_test_amazon:
          when: << pipeline.parameters.build_amazon >>
          type: approval
          requires:
            - deploy_internal
      - manual_test_gplay:
          type: approval
          requires:
            - deploy_internal
      - ready_to_deploy_amazon:
          type: approval
          requires:
            - manual_test_amazon
      - ready_to_deploy_gplay:
          type: approval
          requires:
            - manual_test_gplay
      - archive:
          requires:
            - ready_to_deploy_amazon
            - ready_to_deploy_gplay
      - stage_roll_out:
          requires:
            - ready_to_deploy_gplay
          filters:
            branches:
              only:
                - master
                - release
      - ready_to_full_release:
          type: approval
          requires:
            - stage_roll_out
            - ready_to_deploy_amazon
      - full_release:
          requires:
            - ready_to_full_release
          filters:
            branches:
              only:
                - master
                - release

jobs:
  checkout:
    steps:
      - checkout
  precondition_check:
    steps:
  download_dependencies:
    steps:
      # generate a checksum over all build.gradle files and buildSrc folder
      - run:
          name: Generate cache key
          command: .circleci/checksum.sh /tmp/checksum.txt

      # download and cache dependencies
      - restore_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}

      # https://blog.danlew.net/2015/09/09/dont-use-dynamic-versions-for-your-dependencies/
      # androidDependencies vs dependencies vs buildscriptDependencies
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      # save cache
      - save_cache:
          key: gradle-{{ checksum "/tmp/checksum.txt" }}
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper
  build:
    steps:
      - run:
            name: Build
            command: ./gradlew assemble
      - when:
          condition: << pipeline.parameters.build_amazon >>

  unit_test:
    steps:
      - run:
          name: Run Unit Tests
          command: ./gradlew test

  instrumentation_test:
    steps:
      - run:
          name: Run Unit Tests
          command: ./gradlew connectedAndroidTest

  integration_test:
    steps:

  automatic_test:
    steps:

  lint:
    steps:

  sonar_qube:
    steps:

  espresso_test:
    steps:

  deploy_internal:
    steps:

  manual_test_amazon:
    steps:
      - slack/approval-notification:
          message: Pending approval
          webhook: webhook

  manual_test_gplay:
    steps:

      # Specified persons only can approve the workflow
      # approve via Slack
      - slack/approval-notification:
          message: Pending approval
          webhook: webhook

  archive:
    steps:

  stage_roll_out:
    # publish to stage roll-out
#    - run:
#        name: Publish to Google Play Console
#        command: ./gradlew publishGoogleBundle -Dfsfadspfkasoš

  ready_to_deploy_amazon:
    steps:

  ready_to_deploy_gplay:
    steps:

  ready_to_full_release:
    steps:

  full_release:
    steps: